package com.bojue.bs.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bojue.bsapp.course.db.CourseEntity;

import com.bojue.bs.db.CourseEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseEntityDaoConfig;

    private final CourseEntityDao courseEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseEntityDaoConfig = daoConfigMap.get(CourseEntityDao.class).clone();
        courseEntityDaoConfig.initIdentityScope(type);

        courseEntityDao = new CourseEntityDao(courseEntityDaoConfig, this);

        registerDao(CourseEntity.class, courseEntityDao);
    }
    
    public void clear() {
        courseEntityDaoConfig.clearIdentityScope();
    }

    public CourseEntityDao getCourseEntityDao() {
        return courseEntityDao;
    }

}
